name: Deploy to S3

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチを指定します

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js project
        run: |
          npm run build
          npm run export

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # 使用するリージョン

      - name: Sync files to S3
        run: |
          aws s3 sync out/ s3://your-s3-bucket-name/ --delete

      - name: Invalidate CloudFront (optional)
        run: |
          aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
